# customize your experience
MIN_PLAYERS: 2
MAX_PLAYERS: 6

WINDOW_HEIGHT: 400
WINDOW_WIDTH: 500

BIG_FONT: 24
SMALL_FONT: 16

COLORS: RED, BLUE, ORANGE, GREEN, MAGENTA, CYAN, YELLOW, BLACK, LIGHT_GRAY, PINK, DARK_GRAY, GRAY