# customize your experience
MIN_PLAYERS: 2
MAX_PLAYERS: 6

WINDOW_HEIGHT: 400
WINDOW_WIDTH: 500

FONT_NAME: ARIAL
BIG_FONT: 26
SMALL_FONT: 16

RULES_FILE: rules.txt

COLORS: RED, BLUE, ORANGE, GREEN, MAGENTA, CYAN, YELLOW, BLACK, LIGHT_GRAY, PINK, DARK_GRAY, GRAY