MIN_GIOCATORI: 2
MAX_GIOCATORI: 4

WINDOW_HEIGHT: 400
WINDOW_WIDTH: 500

Color:
  - RED
  - BLUE
  - ORANGE
  - GREEN
  - MAGENTA
  - CYAN
  - YELLOW
  - BLACK
  - LIGHT_GRAY
  - PINK
  - DARK_GRAY
  - GRAY