# For tests: VALID CONFIGURATION (not a default one)

MIN_PLAYERS: 2
MAX_PLAYERS: 5

WINDOW_HEIGHT: 400
WINDOW_WIDTH: 600

FONT_NAME: ARIAL
BIG_FONT: 40
SMALL_FONT: 10

RULES_FILE: rules.txt

COLORS: RED, BLUE, ORANGE, GREEN, BLACK