# Customize your experience

MIN_PLAYERS: 2
MAX_PLAYERS: 6

NUM_DICE: 2
SIDES_PER_DIE: 6

FONT_NAME: ARIAL
BIG_FONT: 32
SMALL_FONT: 20

INIT_BALANCE: 100

RULES_FILE: rules/rules.txt
CARDS_FILE: cards/cards.json

COLORS: RED, BLUE, ORANGE, GREEN, MAGENTA, CYAN, YELLOW, BLACK, LIGHT_GRAY, PINK, DARK_GRAY, GRAY