# Customize your experience

MIN_PLAYERS: 2
MAX_PLAYERS: 6

NUM_DICE: 2
SIDES_PER_DIE: 2

FONT_NAME: SansSerif
BIG_FONT: 30
SMALL_FONT: 16

INIT_BALANCE: 2000

RULES_FILE: rules/rules.txt

CARDS_FILE: cards/final_cards.json
DECK_FILE: cards/DeckCard.txt

COLORS: RED, BLUE, ORANGE, GREEN, MAGENTA, CYAN, YELLOW, BLACK, LIGHT_GRAY, PINK, DARK_GRAY, GRAY