# Customize your experience

MIN_PLAYERS: 2
MAX_PLAYERS: 6

FONT_NAME: ARIAL
BIG_FONT: 32
SMALL_FONT: 20

INIT_BALANCE: 2000

RULES_FILE: rules/rules.txt

COLORS: RED, BLUE, ORANGE, GREEN, MAGENTA, CYAN, YELLOW, BLACK, LIGHT_GRAY, PINK, DARK_GRAY, GRAY