# For tests: VALID CONFIGURATION (not a default one)

MIN_PLAYERS: 2
MAX_PLAYERS: 5

WINDOW_HEIGHT: 400
WINDOW_WIDTH: 500

FONT_NAME: ARIAL
BIG_FONT: 26
SMALL_FONT: 16

INIT_BALANCE: 2000

RULES_FILE: rules/rules.txt

COLORS: RED, BLUE, ORANGE, GREEN, MAGENTA